spring.application.name=foodshare


# PostgreSQL Database

spring.datasource.url=jdbc:postgresql://localhost:5432/foodshare_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


# Google OAuth2

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# Gmail SMTP

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Password Reset

app.mail.from=${MAIL_USERNAME}
app.base-url=${APP_BASE_URL:http://localhost:8080}


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Thymeleaf and Development

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true