spring.application.name=foodshare

spring.datasource.url=jdbc:postgresql://localhost:5432/foodshare_db
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=${DB_PASSWORD}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
>>>>>>> ac053f9 (feat: add Google OAuth2 authentication)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# =========================
# PASSWORD RESET EMAIL
# =========================

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:no-reply@localhost}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM:no-reply@localhost}
app.base-url=${APP_BASE_URL:http://localhost:8080}
