spring.application.name=foodshare

spring.datasource.url=jdbc:postgresql://localhost:5432/foodshare_db
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=XXXX
=======
spring.datasource.password=
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
>>>>>>> ac053f9 (feat: add Google OAuth2 authentication)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
