CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 display_name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 role VARCHAR(20) NOT NULL DEFAULT 'USER', created_at TIMESTAMP NOT NULL,
 CONSTRAINT user_role CHECK (role IN ('USER','ADMIN'))
);
CREATE UNIQUE INDEX users_email_normalized ON users (lower(email));
CREATE TABLE user_profile_images (
 user_id BIGINT PRIMARY KEY REFERENCES users(id), image_data BYTEA NOT NULL, content_type VARCHAR(30) NOT NULL
);
CREATE TABLE password_reset_tokens (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token_hash VARCHAR(64) NOT NULL UNIQUE,
 user_id BIGINT NOT NULL REFERENCES users(id), expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 used_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE NOT NULL, version BIGINT
);
CREATE INDEX reset_user_idx ON password_reset_tokens(user_id);
CREATE TABLE food_posts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES users(id),
 title VARCHAR(150) NOT NULL, description VARCHAR(1000), category VARCHAR(20) NOT NULL,
 quantity INTEGER NOT NULL, reserved_quantity INTEGER NOT NULL DEFAULT 0, collected_quantity INTEGER NOT NULL DEFAULT 0,
 unit VARCHAR(50) NOT NULL, pickup_location_name VARCHAR(255) NOT NULL,
 latitude NUMERIC(10,7) NOT NULL, longitude NUMERIC(10,7) NOT NULL,
 available_from TIMESTAMP NOT NULL, available_until TIMESTAMP NOT NULL, status VARCHAR(20) NOT NULL,
 allergens VARCHAR(500), created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, version BIGINT,
 CONSTRAINT post_quantity CHECK (quantity>0 AND reserved_quantity>=0 AND collected_quantity>=0 AND reserved_quantity+collected_quantity<=quantity),
 CONSTRAINT post_times CHECK (available_until>available_from),
 CONSTRAINT post_location CHECK (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180),
 CONSTRAINT post_category CHECK (category IN ('FOOD','DRINK','SNACK')),
 CONSTRAINT post_status CHECK (status IN ('AVAILABLE','LOW_STOCK','CLAIMED','EXPIRED','CANCELLED'))
);
CREATE INDEX posts_owner_idx ON food_posts(owner_id,created_at DESC);
CREATE INDEX posts_discovery_idx ON food_posts(status,available_until,category);
CREATE INDEX posts_location_idx ON food_posts(latitude,longitude);
CREATE TABLE food_post_images (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL UNIQUE REFERENCES food_posts(id), filename VARCHAR(100) NOT NULL
);
CREATE TABLE reservations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL REFERENCES food_posts(id),
 member_id BIGINT NOT NULL REFERENCES users(id), quantity INTEGER NOT NULL CHECK(quantity>0), status VARCHAR(20) NOT NULL,
 request_key VARCHAR(64) NOT NULL, pickup_hash VARCHAR(100) NOT NULL, pickup_encrypted VARCHAR(255) NOT NULL,
 failed_attempts INTEGER NOT NULL DEFAULT 0, locked_until TIMESTAMP, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, version BIGINT,
 UNIQUE(member_id,request_key), CONSTRAINT reservation_status CHECK (status IN ('RESERVED','COLLECTED','CANCELLED','EXPIRED'))
);
CREATE UNIQUE INDEX reservations_active_unique ON reservations(post_id,member_id) WHERE status='RESERVED';
CREATE INDEX reservations_member_idx ON reservations(member_id,created_at DESC);
CREATE INDEX reservations_post_idx ON reservations(post_id,status);
CREATE TABLE notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
 title VARCHAR(160) NOT NULL, message VARCHAR(500) NOT NULL, href VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL, read_at TIMESTAMP
);
CREATE INDEX notifications_user_idx ON notifications(user_id,created_at DESC);
CREATE TABLE reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL REFERENCES food_posts(id), reporter_id BIGINT NOT NULL REFERENCES users(id),
 reason VARCHAR(1000) NOT NULL, status VARCHAR(20) NOT NULL, resolution VARCHAR(1000), reviewer_id BIGINT REFERENCES users(id),
 created_at TIMESTAMP NOT NULL, resolved_at TIMESTAMP, version BIGINT
);
CREATE INDEX reports_status_idx ON reports(status,created_at DESC);
CREATE TABLE audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id BIGINT NOT NULL REFERENCES users(id),
 action VARCHAR(80) NOT NULL, target_type VARCHAR(80) NOT NULL, target_id BIGINT NOT NULL,
 reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE INDEX audit_actor_idx ON audit_events(actor_id,created_at DESC);
