-- Keep the original image table and rows, but allow a small ordered gallery per post.
ALTER TABLE food_post_images DROP CONSTRAINT IF EXISTS food_post_images_post_id_key;
ALTER TABLE food_post_images ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS food_post_images_post_order_idx
  ON food_post_images(post_id, sort_order, id);

CREATE TABLE IF NOT EXISTS post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES food_posts(id),
  author_id BIGINT NOT NULL REFERENCES users(id),
  body VARCHAR(800) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  deleted_by_id BIGINT REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS post_comments_post_idx ON post_comments(post_id, created_at);

-- Existing post reports remain unchanged; comment_id distinguishes reports about a comment.
ALTER TABLE reports ADD COLUMN IF NOT EXISTS comment_id BIGINT REFERENCES post_comments(id);
CREATE INDEX IF NOT EXISTS reports_comment_idx ON reports(comment_id, status);

CREATE TABLE IF NOT EXISTS notification_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
  categories VARCHAR(100) NOT NULL DEFAULT '',
  keywords VARCHAR(300) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS dedupe_key VARCHAR(255);
CREATE INDEX IF NOT EXISTS notifications_dedupe_idx ON notifications(user_id, dedupe_key);
