CREATE TABLE IF NOT EXISTS saved_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  post_id BIGINT NOT NULL REFERENCES food_posts(id),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT saved_posts_user_post_key UNIQUE (user_id, post_id)
);
CREATE INDEX IF NOT EXISTS saved_posts_user_created_idx ON saved_posts(user_id, created_at DESC);
